package com.sadwyn.iceandfire;



public interface Constants {
    String BACKGROUND_IMAGE_URL = "http://wallpaperscraft.ru/image/linii_svetlyy_fon_yarkiy_43975_540x960.jpg";
    String BASE_URL = "http://anapioficeandfire.com/";
    int DEFAULT_SPAN_COUNT = 2;
    int REQUEST_FOR_WRITE_TO_CSV = 1;
    String LANG_PREF = "LANG_PREF";
    String DATA_SOURCE_PREF = "DATA_SOURCE_PREF";
    String CHARACTER_KEY = "CHARACTER_KEY";
    String CHARACTERS_FRAGMENT_TAG = "CHARACTERS_FRAGMENT_TAG";
    String DETAIL_FRAGMENT_TAG = "DETAIL_FRAGMENT_TAG";
    String SETTINGS_FRAGMENT_TAG = "SETTINGS_FRAGMENT_TAG";
    String SEND_TO_SERVICE_KEY = "SEND_TO_SERVICE_KEY";
    String WIDGET_INFO_GOTH = "WIDGET_INFO_GOTH";
    String PREV_HERO_SWITCH = "PREV_HERO_SWITCH";
    String NEXT_HERO_SWITCH = "NEXT_HERO_SWITCH";
    String HERO_DETAIL_REQUESTED = "HERO_DETAIL_REQUESTED";
    String INCOMING_INTENT = "INCOMING_INTENT";
    String WRAPPED_CHARACTER_FROM_RECEIVER = "WRAPPED_CHARACTER_FROM_RECEIVER";
    String START_DETAIL_FROM_WIDGET = "START_DETAIL_FROM_WIDGET";
    String PREV_HERO_ID = "PREV_HERO_ID";
    String NEXT_HERO_ID = "NEXT_HERO_ID";
    String CURRENT_HERO_ID = "CURRENT_HERO_ID";
    String PREV_HERO_NAME = "PREV_HERO_NAME";
    String NEXT_HERO_NAME = "NEXT_HERO_NAME";


}
